library(randtests)
library(hexbin)
library(Hmisc)

make.plots <- function(df, title="") {
  for (thr in c(3, 5, 10)) {
    df.subset <- subset(df, nsites >= thr)
    hist(df.subset$p, breaks=1000, main=paste0("WaW p-value distribution (", nrow(df.subset), " ", title, " >=", thr," sites)"),
         xlab="", ylab="")
    hist(df.subset$p.adj, breaks=1000, main=paste0("WaW p-value distribution (", nrow(df.subset), " ", title, " >=", thr," sites)"),
         xlab="", ylab="")    
    
    plot(df.subset$len, df.subset$p, main=capitalize(title),
         xlab="Protein length", ylab="P-value")
    
    # df.subset.trimmed <- subset(df.subset, len > 100)
    # plot(hexbin(df.subset.trimmed$len, df.subset.trimmed$p), main=capitalize(title),
    #      xlab="Protein length", ylab="P-value")
    plot(df.subset.trimmed$len, df.subset.trimmed$p, main=paste(capitalize(title), "(length > 100)"),
        xlab="Protein length", ylab="P-value")
  }
}

process.runs <- function(df, stat, op, stat_thr) {
  opfun <- match.fun(FUN = op) 
  v <- as.numeric(opfun(df[, stat], stat_thr))
  nsites <- sum(v)
  res <- runs.test(v, "left.sided", threshold=0.5)
  data.frame(p=res$p.value, nsites=nsites, len=length(v))
}

runs.globular <- ddply(pdb_master_globular, c("stable_id", "pdb_id"), process.runs, "omega", ">", 1)

## NEW
runs.all_0.05 <- ddply(slr_all, c("stable_id"), process.runs, "Adj.Pval", "<", 0.05)
runs.all_0.1 <- ddply(slr_all, c("stable_id"), process.runs, "Adj.Pval", "<", 0.1)
runs.all_0.2 <- ddply(slr_all, c("stable_id"), process.runs, "Adj.Pval", "<", 0.2)
runs.all_0.5 <- ddply(slr_all, c("stable_id"), process.runs, "Adj.Pval", "<", 0.5)

## So the data structure should be a df stable ids + all pvals


runs.globular$p.adj <- p.adjust(runs.globular$p, method="BH")
sum(runs.globular$p.adj < 0.05, na.rm=T)

pdf("WaW_globular.pdf", height=7, width=9)
make.plots(runs.globular, title="globular w/structure")
dev.off()

# TODO some example plots? Perhaps in the style generated by runs.test()

runs.membrane <- ddply(subset(pdb_master, tm_full != "Globular"), c("stable_id", "pdb_id"), process.runs, "omega", ">", 1)

runs.membrane$p.adj <- p.adjust(runs.membrane$p, method="BH")
sum(runs.membrane$p.adj < 0.05, na.rm=T)

pdf("WaW_membrane.pdf", height=7, width=9)
make.plots(runs.membrane, title="membrane w/structure")
dev.off()


runs.all <- ddply(slr_all, c("stable_id"), process.runs, "Omega", ">", 1)

runs.all$p.adj <- p.adjust(runs.all$p, method="BH")
sum(runs.all$p.adj < 0.05, na.rm=T)

pdf("WaW_all.pdf", height=7, width=9)
make.plots(runs.all, title="all")
dev.off()

runs.all.mtc <- ddply(slr_all, c("stable_id"), process.runs, "lower", ">", 1)

runs.all.mtc$p.adj <- p.adjust(runs.all.mtc$p, method="BH")
sum(runs.all.mtc$p.adj < 0.05, na.rm=T)

pdf("WaW_all_genewise_MTC.pdf", height=7, width=9)
make.plots(runs.all.mtc, title="all (genewise MTC)")
dev.off()

runs.all.gmtc <- ddply(slr_all, c("stable_id"), process.runs, "Adj.Pval", "<", 0.05)

runs.all.gmtc$p.adj <- p.adjust(runs.all.gmtc$p, method="BH")
sum(runs.all.gmtc$p.adj < 0.05, na.rm=T)

pdf("WaW_all_genomewise_MTC.pdf", height=7, width=9)
make.plots(runs.all.gmtc, title="all (genewise MTC)")
dev.off()


# Example plots
runs.all.subset <- subset(runs.all.gmtc, nsites >= 5)
order(runs.all.subset$p)[1:10]
runs.all.subset[order(runs.all.subset$p)[1:10], ]

pdf("example_plots.pdf", height=7, width=9)
runs.test(as.numeric(subset(slr_all, stable_id == "ENSP00000016913")$Adj.Pval < 0.05), "left.sided", threshold=0.5, plot=T)
runs.test(as.numeric(subset(slr_all, stable_id == "ENSP00000350418")$Adj.Pval < 0.05), "left.sided", threshold=0.5, plot=T)
runs.test(as.numeric(subset(slr_all, stable_id == "ENSP00000308279")$Adj.Pval < 0.05), "left.sided", threshold=0.5, plot=T)
runs.test(as.numeric(subset(slr_all, stable_id == "ENSP00000437563")$Adj.Pval < 0.05), "left.sided", threshold=0.5, plot=T)
runs.test(as.numeric(subset(slr_all, stable_id == "ENSP00000438038")$Adj.Pval < 0.05), "left.sided", threshold=0.5, plot=T)
dev.off()

process.runs(subset(slr_all, stable_id == "ENSP00000480132"))